/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./src/**/*.{html,js}"],
    darkMode: "class",
    theme: {
        extend: {
            backgroundColor: {
                "sb-dark": "#231b2e",
                sb: "#dde4e4",
                sbr: "#ced9d9",
                "sbr-dark": "#120822",
                player: "#c0d8d8",
                "player-dark": "#130c1c",
                "b-main": "#ced9d9",
                "b-main-dark": "#170f23",
                "b-button": "#0e8080",
                "b-button-dark": "#9B4DE0",
                "b-active": "#e7eded",
                "b-active-dark": "#3a3344",
                modal: "#34224f",
                bmodal: "#ffbd00",
                overlay: "rgba(0,0,0,0.5)",
                search: "#dde4e4",
                "search-dark": "#2f2739",
            },
            colors: {
                main: "#696969",
                "main-dark": "#dadada",
                "main-100": "#0f7070 ",
                "main-100-dark": "#ffffff80",
                light: "#fff",
                dark: "#32323d",
                "main-hv": "#0f7070",
                "main-hv-dark": "#c273ed",
                "t-border": "#393243",
            },
        },
    },
    plugins: [],
};
